#!/usr/bin/env node
/**
 * snap-x MCP Server
 *
 * Exposes snap-x image generation as MCP tools.
 * Compatible with Cursor, Windsurf, Claude Desktop, and any MCP client.
 *
 * Tools:
 *   - generate_images    build the full image pack for a project
 *   - init_config        scaffold snap-x.config.json + templates
 *   - list_formats       list available formats with dimensions
 */

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import { execFile } from "child_process";
import { promisify } from "util";
import path from "path";
import fs from "fs/promises";

const execFileAsync = promisify(execFile);

// Formats reference
const FORMATS = {
  og:        { width: 1200, height: 630,  description: "Open Graph / Twitter card" },
  cover:     { width: 1500, height: 500,  description: "GitHub / Twitter banner" },
  thumbnail: { width: 1280, height: 720,  description: "YouTube / blog thumbnail" },
  poster:    { width: 1080, height: 1920, description: "Instagram story / vertical" },
  readme:    { width: 1280, height: 640,  description: "GitHub README card" },
};

// ─── Server setup ─────────────────────────────────────────────────────────────

const server = new Server(
  { name: "snap-x", version: "0.2.0" },
  { capabilities: { tools: {} } }
);

// ─── List tools ───────────────────────────────────────────────────────────────

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    {
      name: "generate_images",
      description:
        "Generate a full social image pack (OG, cover, thumbnail, poster, README card) for a project directory using snap-x. Uses Playwright (HTML templates) or Satori (--fast mode).",
      inputSchema: {
        type: "object",
        properties: {
          projectDir: {
            type: "string",
            description: "Absolute path to the project directory. Defaults to current working directory.",
          },
          formats: {
            type: "array",
            items: { type: "string", enum: ["og", "cover", "thumbnail", "poster", "readme"] },
            description: "Which formats to generate. Defaults to all.",
          },
          outDir: {
            type: "string",
            description: "Output directory for generated images. Defaults to ./snap-output.",
          },
          title: { type: "string", description: "Override project title." },
          description: { type: "string", description: "Override project description." },
          domain: { type: "string", description: "Override domain/brand name." },
          tags: {
            type: "array",
            items: { type: "string" },
            description: "Override tags (max 3).",
          },
          theme: {
            type: "string",
            enum: ["dark", "light"],
            description: "Visual theme. Defaults to dark.",
          },
          font: { type: "string", description: "Google Font family name. Defaults to Inter." },
          fast: {
            type: "boolean",
            description: "Use Satori fallback (no browser required). Defaults to false.",
          },
        },
        required: [],
      },
    },
    {
      name: "init_config",
      description:
        "Scaffold snap-x.config.json and HTML templates in a project directory. Safe to run — won't overwrite existing files unless force=true.",
      inputSchema: {
        type: "object",
        properties: {
          projectDir: {
            type: "string",
            description: "Absolute path to the project directory.",
          },
          force: {
            type: "boolean",
            description: "Overwrite existing config and templates. Defaults to false.",
          },
        },
        required: [],
      },
    },
    {
      name: "list_formats",
      description:
        "List all available snap-x image formats with their dimensions and use cases.",
      inputSchema: {
        type: "object",
        properties: {},
        required: [],
      },
    },
  ],
}));

// ─── Call tool ────────────────────────────────────────────────────────────────

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  if (name === "list_formats") {
    const lines = Object.entries(FORMATS).map(
      ([id, f]) => `• ${id.padEnd(10)} ${f.width}×${f.height}  ${f.description}`
    );
    return {
      content: [
        {
          type: "text",
          text: `snap-x formats:\n\n${lines.join("\n")}\n\nAll formats are generated by default. Use the "formats" parameter to select specific ones.`,
        },
      ],
    };
  }

  if (name === "init_config") {
    const projectDir = args.projectDir ?? process.cwd();
    const force = args.force ?? false;

    try {
      const cliArgs = ["snap-x", "init"];
      if (force) cliArgs.push("--force");
      cliArgs.push("--project", projectDir);

      const { stdout, stderr } = await execFileAsync("npx", cliArgs, {
        cwd: projectDir,
        timeout: 30_000,
      });

      return {
        content: [
          {
            type: "text",
            text: `snap-x init completed for ${projectDir}\n\n${stdout}${stderr ? `\nWarnings:\n${stderr}` : ""}`,
          },
        ],
      };
    } catch (err) {
      return {
        content: [{ type: "text", text: `Error running snap-x init: ${err.message}` }],
        isError: true,
      };
    }
  }

  if (name === "generate_images") {
    const projectDir = args.projectDir ?? process.cwd();
    const outDir = args.outDir ?? path.join(projectDir, "snap-output");
    const fast = args.fast ?? false;

    // Build CLI args
    const cliArgs = ["snap-x", "build"];

    if (args.formats?.length) {
      // Run once per format (CLI supports single format at a time)
      // We'll pass a single format and loop if needed
    }
    if (args.title)       cliArgs.push("--title", args.title);
    if (args.description) cliArgs.push("--desc", args.description);
    if (args.domain)      cliArgs.push("--domain", args.domain);
    if (args.tags?.length) cliArgs.push("--tags", args.tags.join(","));
    if (args.theme)       cliArgs.push("--theme", args.theme);
    if (args.font)        cliArgs.push("--font", args.font);
    if (outDir)           cliArgs.push("--out", outDir);
    if (fast)             cliArgs.push("--fast");
    if (args.formats?.length === 1) cliArgs.push("--format", args.formats[0]);
    cliArgs.push("--project", projectDir);

    try {
      const { stdout, stderr } = await execFileAsync("npx", cliArgs, {
        cwd: projectDir,
        timeout: 120_000,
      });

      // List generated files
      let generatedFiles = [];
      try {
        const files = await fs.readdir(outDir);
        generatedFiles = files.filter((f) => f.endsWith(".png"));
      } catch {}

      return {
        content: [
          {
            type: "text",
            text: [
              `snap-x build completed.`,
              `Output directory: ${outDir}`,
              generatedFiles.length > 0
                ? `\nGenerated files:\n${generatedFiles.map((f) => `  • ${f}`).join("\n")}`
                : "",
              stdout ? `\nOutput:\n${stdout}` : "",
              stderr ? `\nWarnings:\n${stderr}` : "",
            ]
              .filter(Boolean)
              .join("\n"),
          },
        ],
      };
    } catch (err) {
      const hint = err.message.includes("install-browser")
        ? "\n\nTip: Run `npx snap-x install-browser` to install Playwright Chromium, or pass fast=true to use Satori instead."
        : "";
      return {
        content: [
          { type: "text", text: `Error running snap-x build: ${err.message}${hint}` },
        ],
        isError: true,
      };
    }
  }

  return {
    content: [{ type: "text", text: `Unknown tool: ${name}` }],
    isError: true,
  };
});

// ─── Start ────────────────────────────────────────────────────────────────────

const transport = new StdioServerTransport();
await server.connect(transport);
